# Setup
title:        Klotski's Blog
tagline:      We are in a f**king corrupted world, unfortunately.
baseurl:      ""
paginate:     1

# About/contact
author:       
  name:       Klotski
  url:        https://klotski.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
